---
- hosts: all
  become: yes
  tasks:

  - name: Install epel-release
    ansible.builtin.yum:
      name: epel-release
      state: present

  - name: Install packages
    ansible.builtin.yum:
      name:
      - bind
      - bind-utils
      - vim
      state: latest 

  - name: Set timezone
    community.general.timezone:
      name: Europe/Moscow
    notify:
      - Restart Chrony service

  - name: Accept login with password from sshd
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication no$'
      line: 'PasswordAuthentication yes'
      state: present
    notify:
      - Restart sshd

  - name: Copy transferkey to all servers and clients
    ansible.builtin.copy:
      src: named.zonetransfer.key
      dest: /etc/named.zonetransfer.key
      owner: root
      group: named
      mode: '0644'

  - name: Copy resolv.conf to the servers
    ansible.builtin.template:
      src: servers-resolv.conf.j2
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: '0644'
    when: (ansible_hostname == 'ns01' or ansible_hostname == 'ns02')
  
  handlers:

  - name: Restart Chrony service
    ansible.builtin.service:
      name: chronyd
      state: restarted

  - name: Restart sshd
    ansible.builtin.service:
      name: sshd
      state: restarted
      enabled: true


- hosts: ns01
  become: yes
  tasks:

  - name: Copy named.conf
    ansible.builtin.copy:
      src: files/master-named.conf
      dest: /etc/named.conf
      owner: root
      group: named
      mode: '0640'
    notify: Restart named

  - name: Copy zones
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: /etc/named/
      owner: root
      group: named
      mode: '0660'
    with_fileglob:
      - 'named.d*'
      - named.newdns.lab
    notify: Restart named

  - name: Set /etc/named permissions
    ansible.builtin.file:
      path: /etc/named
      owner: root
      group: named
      mode: '0670'

  handlers:

  - name: Restart named
    service:
      name: named
      state: restarted
      enabled: yes


- hosts: ns02
  become: yes
  tasks:

  - name: Copy named.conf
    ansible.builtin.copy:
      src: files/slave-named.conf
      dest: /etc/named.conf
      owner: root
      group: named
      mode: '0640'
    notify: Restart named

  - name: Set /etc/named permissions
    ansible.builtin.file:
      path: /etc/named
      owner: root
      group: named
      mode: '0670'

  handlers:

  - name: Restart named
    service:
      name: named
      state: restarted
      enabled: yes

- hosts: client,client2
  become: yes
  tasks:
  - name: Copy resolv.conf to the client
    copy:
      src: files/client-resolv.conf
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: '0644'

  - name: Copy rndc conf file
    copy:
      src: files/rndc.conf
      dest: /home/vagrant/rndc.conf
      owner: vagrant
      group: vagrant
      mode: '0644'

  - name: Copy motd to the client
    copy:
      src: files/client-motd
      dest: /etc/motd
      owner: root
      group: root
      mode: '0644'




